[project]
name = "setup"
version = "0.1.0"
description = ""
authors = [{name = "HAT Inc.", email = "maintainer@example.com"}]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
    "openvino>=2026.4.1,<2027",
    "transformers>=5.19.0,<6",
    "torch>=2.14.1,<3",
]

[tool.poetry]
packages = [{include = "setup", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
